# Generated by Django 5.2.7 on 2025-11-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpreferences",
            name="font_size",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="language",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="notifications_email",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="notifications_sms",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="theme",
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="two_factor_enabled",
        ),
        migrations.AlterField(
            model_name="securitylog",
            name="activity",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("password_change", "Password Change"),
                    ("profile_update", "Profile Update"),
                    ("failed_login", "Failed Login"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="OTPVerification",
        ),
    ]
