# Generated by Django 5.2.7 on 2025-11-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_remove_userpreferences_font_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="font_size",
            field=models.CharField(
                choices=[("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="theme",
            field=models.CharField(
                choices=[("dark", "Dark Mode"), ("light", "Light Mode")],
                default="dark",
                max_length=10,
            ),
        ),
    ]
