# Generated by Django 5.2.7 on 2025-11-15 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("transactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FraudDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewed", "Reviewed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "unusual_amount",
                    models.BooleanField(
                        default=False,
                        help_text="Amount is significantly higher than usual",
                    ),
                ),
                (
                    "rapid_transactions",
                    models.BooleanField(
                        default=False, help_text="Multiple transactions in short time"
                    ),
                ),
                (
                    "unusual_time",
                    models.BooleanField(
                        default=False, help_text="Transaction at unusual hours"
                    ),
                ),
                (
                    "new_recipient",
                    models.BooleanField(
                        default=False, help_text="First transaction to this recipient"
                    ),
                ),
                (
                    "geographic_anomaly",
                    models.BooleanField(
                        default=False, help_text="Transaction from unusual location"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Detailed reason for flagging"
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Admin notes")),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fraud_detections",
                        to="accounts.account",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fraud_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fraud_detection",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Fraud Detections",
                "ordering": ["-detected_at"],
            },
        ),
    ]
